### ISSUE TITLE
edits to HEM interface mock-ups - all chemicals/all products

### ISSUE THREAD

**Issue by kdionisio** [quanted/hem_app#7]
Add option for user to select 'all chemicals' or 'all products'

**Comment by dmlyons2** [comment]
@kdionisio - I do not understand why we are doing this and who it is being done for :) Example - it may not make sense to pick all chemicals or products if the goal is to have the program office be able to download all of the data. If that is the case we might have a link to a MySQL dump of the database or something similar.  Please take a look at this write-up on [user stories](https://www.mountaingoatsoftware.com/agile/user-stories)

Perhaps you can put this in terms of:  

As a _type_ of user_
I want _some goal_
so that _some reason_

This is the template that we want to strive for on features such as this one. Bugs and such do not need to follow the template.

**Comment by kdionisio** [comment]
removing this from 'To Do's' for now...

**Comment by kdionisio** [comment]
I changed the milestone this issue was assigned to, but how do I move it out of this project, since this is no longer needed for the demo launch??

**Comment by kdionisio** [comment]
going in different direction for project
