### ISSUE TITLE
Plot of pop distro of mean annual dose by chemical

### ISSUE THREAD

**Issue by dmlyons2** [quanted/hem_app#93]
Think highcharts

**Comment by kdionisio** [comment]
@dmlyons2 We can discuss before you start this ticket if needed.

First - use ONLY the subset of rows from the dose table that are included in the dose download .csv file

1. for each person, for each day (ie for every row), add dir_derm_abs + dir_ingest_abs + dir_inhal_abs = daily systemic dose (so daily systemic dose will become a new column)

2. for each person, take mean of daily systemic dose over days 1-364 (i.e., annual average; note our 'year' has 364 days) = annual average systemic dose

3. At this point there is a data set of person vs. annual average systemic dose. We now want to plot a probability density plot, or the percent of the population (y axis) vs annual average systemic dose (x axis) for the chemical. This is an example, but rather than many lines, for now there is just one line per chemical.
![image](https://cloud.githubusercontent.com/assets/16561576/26592688/7d18b408-452f-11e7-98c9-563bc4183ac0.png)

https://stackoverflow.com/questions/10640759/how-to-get-the-cumulative-distribution-function-with-numpy
Essentially we are creating a histogram and then plotting the best fit line. I do NOT need the histogram, just the best fit line portion.

In HighCharts there is a 'histogram' option but I didn't see the option to plot the best fit line. I don't know if it's better to create the data set that defines the best fit line and then just plot the line in HighCharts, or to read in the data set of annual average systemic dose by person to HighCharts and let HighCharts create that PDF curve (i.e., the best fit line).

**Comment by dmlyons2** [comment]
``` Python
#!/usr/bin/env python

## pandas version 0.19.0
import pandas as pd

pd.np.random.seed(10)
n_people = 1000
n_days = 364

## Make up a random data frame with random values for the doses
data = pd.DataFrame({'id':pd.np.repeat(pd.np.arange(0,n_people),n_days),
                     'day': pd.np.repeat(pd.np.arange(1,n_days+1),n_people),
                     'dir_derm_abs':pd.np.random.random_sample(n_people*n_days),
                     'dir_ingest_abs':pd.np.random.random_sample(n_people*n_days),
                     "dir_inhal_abs":pd.np.random.random_sample(n_people*n_days)})

data = data[['id','day','dir_derm_abs','dir_ingest_abs','dir_inhal_abs']].copy()

## Daily systemic dose
data['day_sys_dose'] = data.dir_derm_abs + data.dir_ingest_abs + data.dir_inhal_abs

## Annual systemic dose by person
ann_sys_dose = data.groupby(['id']).day_sys_dose.mean().reset_index()

## Get the Histogram

## Get weights so that this is a probability density
weights = pd.np.ones_like(ann_sys_dose.day_sys_dose.tolist()) / len(ann_sys_dose.day_sys_dose.tolist())

## Compute the histogram
hist, bin_edges = pd.np.histogram(ann_sys_dose.day_sys_dose, weights=weights*100, bins=20)

## Center position of bins, if needed
# bin_centers = (bin_edges[:-1] + bin_edges[1:]) / 2.

## Use probability density to get a cumulative density
# cum_dist = pd.np.cumsum(hist)


## Produces a plot of histogram and cumulative density
# import matplotlib as mpl
# import matplotlib.pyplot as plt
# mpl.style.use("default")
# plt.close("all")
# fig = plt.figure()
#
# ax1 = fig.add_subplot(111)
# ax2 = ax1.twinx()
#
# ax1.bar(bin_centers,hist,facecolor='C0',edgecolor='white',width=0.007)
# ax2.plot(bin_centers,cum_dist,c='C2',lw=2)
#
# ax1.set_xlabel("Dose")
# ax1.set_ylabel("Histogram of the Population")
# ax2.set_ylabel("Percent of the Population")
# fig.savefig("dose_hist.png")
```
